[package]
authors = ["David Henningsson <diwic@ubuntu.com>"]
name = "dbus-tokio"
version = "0.4.0"

description = "Makes it possible to use Tokio with D-Bus, which is a bus commonly used on Linux for inter-process communication."
repository = "https://github.com/diwic/dbus-rs"
documentation = "http://docs.rs/dbus-tokio"
keywords = ["D-Bus", "DBus"]
license = "Apache-2.0/MIT"
categories = ["os::unix-apis", "api-bindings", "asynchronous"]
edition = "2018"
readme = "README.md"

[dependencies]
dbus = { path = "../dbus", version = "0.7.1" }
mio = "0.6.14"
futures = "0.3.1"
tokio = "=0.2.0-alpha.6"
tokio-net = "=0.2.0-alpha.6"

[dev-dependencies]
tokio-timer = "0.2.4"


[badges]
is-it-maintained-open-issues = { repository = "diwic/dbus-rs" }
is-it-maintained-issue-resolution = { repository = "diwic/dbus-rs" }
travis-ci = { repository = "diwic/dbus-rs" }
