name: Dbus-rs-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install --no-install-recommends -y libdbus-1-dev dbus at-spi2-core
    - name: Check
      run: cargo check --verbose --all
    - name: Run test (step 1)
      run: cargo test --all -- --nocapture --color always
    - name: Run codegen tests without default features
      run: cd dbus-codegen && cargo test --all --no-default-features -- --nocapture --color always
