name: Dbus-rs-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check --verbose --all
    - name: Run tests
      run:
        cargo test --all -- --nocapture --color always
        cd dbus-codegen && cargo test --all --no-default-features -- --nocapture --color always
